- name: install apache2 & php
  remote_user: azureuser
  hosts: anne_myVM
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: "Install apache2"
      package: name=apache2 state=present
    - name: "Install php-cli"
      package: name=php-cli state=present
    - name: "Install php-gd"
      package: name=php-gd state=present                                    
